// src/graphql/constants.js

// User
const USER_CREATED = "USER_CREATED";
const USER_UPDATED = "USER_UPDATED";
const USER_DELETED = "USER_DELETED";

// Event
const EVENT_CREATED = "EVENT_CREATED";
const EVENT_UPDATED = "EVENT_UPDATED";
const EVENT_DELETED = "EVENT_DELETED";

// Participant
const PARTICIPANT_CREATED = "PARTICIPANT_CREATED";
const PARTICIPANT_UPDATED = "PARTICIPANT_UPDATED";
const PARTICIPANT_DELETED = "PARTICIPANT_DELETED";

module.exports = {
  USER_CREATED,
  USER_UPDATED,
  USER_DELETED,
  EVENT_CREATED,
  EVENT_UPDATED,
  EVENT_DELETED,
  PARTICIPANT_CREATED,
  PARTICIPANT_UPDATED,
  PARTICIPANT_DELETED,
};
